=== PurdueElectricRacing/monorepo/daq/daqapp/hil_config/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",

  "required": ["name", "description", "expect"],

  "properties": {
  "$schema": {
    "type": "string"
  },

    "name": {
      "type": "string"
    },

    "description": {
      "type": "string"
    },

    "tx": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["timestamp", "msg_name", "signals"],

        "properties": {
          "timestamp": {
            "type": "number"
          },

          "msg_name": {
            "type": "string"
          },

          "signals": {
            "type": "object",
            "additionalProperties": {
              "type": "number"
            }
          }
        },

        "additionalProperties": false
      }
    },

    "expect": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["window", "msg_name"],

        "properties": {
          "window": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2
          },

          "msg_name": {
            "type": "string"
          },

          "signals": {
            "type": "object",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "number"
              },
              "minItems": 2,
              "maxItems": 2
            }
          },

          "accept": {
            "type": "string",
            "enum": ["first", "last", "any"],
            "default": "first"
          }
        },

        "additionalProperties": false
      }
    }
  },

  "additionalProperties": false
}

=== PurdueElectricRacing/monorepo/daq/daqapp/hil_config/tests/idk.json
{
	"$schema": "../schema.json",

	"name": "Pack sanity check",
	"description": "Verify thermistor response",

	"tx": [
		{
			"timestamp": 2000,
			"msg_name": "pack_analog",
			"signals": {
				"pack_voltage": 540.0,
				"pack_current": 10.0
			}
		},

		{
			"timestamp": 10000,
			"msg_name": "thermistor_telemetry",
			"signals": {
				"temperature": 35.0,
				"module_num": 1,
    			"thermistor_num": 2
			}
		},

		{
			"msg_name": "canpiler_test",
			"timestamp": 3000,
			"signals": {
				"temperature": 25,
				"current": 10,
				"voltage": 3.3,
				"pressure": 100,
				"status": 1
			}
		}
	],
	"expect": [
		{
			"window": [10000, 10120],
			"msg_name": "thermistor_telemetry",
			"signals": {
				"temperature": [30.0, 40.0]
			}
		}
	]
}

=== PurdueElectricRacing/monorepo/daq/daqapp/hil_config/tests/test_signal_validation.json
{
	"$schema": "../schema.json",

	"name": "Pack sanity check",
	"description": "Verify thermistor response",

	"tx": [
		{
			"timestamp": 15,
			"msg_name": "pack_analog",
			"signals": {
				"pack_voltage": 540.0,
				"pack_current": 10.0
			}
		}
	],
	"expect": [
		{
			"window": [0, 10000],
			"msg_name": "thermistor_telemetry",
			"signals": {
				"temperature": [30.0, 40.0]
			},
			"accept": "last"
		}
	]
}
