=== PurdueElectricRacing/monorepo/firmware/can_library/schema/external_node.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "required": ["node_name"],
    "additionalProperties": false,
    "properties": {
        "node_name": { "type": "string" },
        "bus_name": { "type": "string" },
        "busses": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/$defs/bus_messages"
            },
            "minProperties": 1
        },
        "tx": {
            "type": "array",
            "items": { "$ref": "https://github.com/PER/canpiler/message.schema.json#/$defs/tx_message" }
        },
        "rx": {
            "type": "array",
            "items": { "$ref": "https://github.com/PER/canpiler/message.schema.json#/$defs/rx_message" }
        }
    },
    "oneOf": [
        {
            "required": ["bus_name"],
            "not": { "required": ["busses"] }
        },
        {
            "required": ["busses"],
            "not": {
                "anyOf": [
                    { "required": ["bus_name"] },
                    { "required": ["tx"] },
                    { "required": ["rx"] }
                ]
            }
        }
    ],
    "$defs": {
        "bus_messages": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "tx": {
                    "type": "array",
                    "items": { "$ref": "https://github.com/PER/canpiler/message.schema.json#/$defs/tx_message" }
                },
                "rx": {
                    "type": "array",
                    "items": { "$ref": "https://github.com/PER/canpiler/message.schema.json#/$defs/rx_message" }
                }
            }
        }
    }
}

=== PurdueElectricRacing/monorepo/firmware/generators/configs/external_nodes/INVERTER_A.json
{
    "node_name": "INVERTER_A",
    "bus_name": "MCAN",
    "tx": [
        {
            "message_name": "INVA_CRIT",
            "description": "Contains the status word and actual values",
            "signals": [
                {
                    "signal_name": "AMK_ActualSpeed",
                    "description": "Actual speed value",
                    "data_type": "int16_t",
                    "unit": "rpm"
                },
                {
                    "signal_name": "AMK_ActualTorque",
                    "description": "Actual torque value",
                    "data_type": "int16_t",
                    "unit": "%",
                    "scale": 0.1
                },
                {
                    "signal_name": "AMK_DisplayOverloadInverter",
                    "data_type": "uint16_t",
                    "scale": 0.1,
                    "unit": "%"
                },
                {
                    "signal_name": "AMK_DisplayOverloadMotor",
                    "data_type": "uint16_t",
                    "scale": 0.1,
                    "unit": "%"
                }
            ],
            "period_ms": 15,
            "id_override": "0x121",
            "priority": 1
        },
        {
            "message_name": "INVA_INFO",
            "description": "Contains the status word and actual values",
            "signals": [
                {
                    "signal_name": "AMK_Status_bReserve",
                    "description": "Status word: RESERVED",
                    "data_type": "uint8_t",
                    "length": 8
                },
                {
                    "signal_name": "AMK_Status_bSystemReady",
                    "description": "Status word: system ready",
                    "data_type": "bool"
                },
                {
                    "signal_name": "AMK_Status_bError",
                    "description": "Status word: error",
                    "data_type": "bool"
                },
                {
                    "signal_name": "AMK_Status_bWarn",
                    "description": "Status word: warning",
                    "data_type": "bool"
                },
                {
                    "signal_name": "AMK_Status_bQuitDcOn",
                    "description": "Status word: HV activation ACK",
                    "data_type": "bool"
                },
                {
                    "signal_name": "AMK_Status_bDcOn",
                    "description": "Status word: HV activation level",
                    "data_type": "bool"
                },
                {
                    "signal_name": "AMK_Status_bQuitInverterOn",
                    "description": "Status word: Controller enable ACK",
                    "data_type": "bool"
                },
                {
                    "signal_name": "AMK_Status_bInverterOn",
                    "description": "Status word: Controller enable level",
                    "data_type": "bool"
                },
                {
                    "signal_name": "AMK_Status_bDerating",
                    "description": "Status word: torque limit activation",
                    "data_type": "bool"
                },
                {
                    "signal_name": "AMK_DCBusVoltage",
                    "description": "Voltage of the DC bus",
                    "data_type": "uint16_t",
                    "unit": "V"
                }
            ],
            "period_ms": 500,
            "id_override": "0x231",
            "priority": 2
        },
        {
            "message_name": "INVA_ERR_1",
            "description": "All error information",
            "signals": [
                {
                    "signal_name": "AMK_DiagnosticNumber",
                    "description": "Error number",
                    "data_type": "uint32_t"
                },
                {
                    "signal_name": "AMK_ErrorInfo1",
                    "description": "Error info",
                    "data_type": "uint32_t"
                }
            ],
            "period_ms": 2000,
            "id_override": "0x441",
            "priority": 4
        },
        {
            "message_name": "INVA_ERR_2",
            "description": "All error information",
            "signals": [
                {
                    "signal_name": "AMK_ErrorInfo2",
                    "description": "Error info",
                    "data_type": "uint32_t"
                },
                {
                    "signal_name": "AMK_ErrorInfo3",
                    "description": "Error info",
                    "data_type": "uint32_t"
                }
            ],
            "period_ms": 2000,
            "id_override": "0x451",
            "priority": 4
        },
        {
            "message_name": "INVA_TEMPS",
            "description": "Contains temperatures",
            "signals": [
                {
                    "signal_name": "AMK_MotorTemp",
                    "description": "Motor temperature",
                    "data_type": "int16_t",
                    "unit": "C",
                    "scale": 0.1
                },
                {
                    "signal_name": "AMK_InverterTemp",
                    "description": "Inverter cold plate temperature",
                    "data_type": "int16_t",
                    "unit": "C",
                    "scale": 0.1
                },
                {
                    "signal_name": "AMK_IGBTTemp",
                    "description": "IGBT temperature",
                    "data_type": "int16_t",
                    "unit": "C",
                    "scale": 0.1
                }
            ],
            "period_ms": 500,
            "id_override": "0x461",
            "priority": 4
        },
        {
            "message_name": "INVA_PHASE_I",
            "description": "All error information",
            "signals": [
                {
                    "signal_name": "AMK_PhaseUCurrent",
                    "description": "INVA Phase U Current",
                    "data_type": "int32_t"
                }
            ],
            "period_ms": 250,
            "id_override": "0x571",
            "priority": 4
        }
    ],
    "rx": [
        {
            "message_name": "INVA_SET"
        }
    ]
}

=== PurdueElectricRacing/monorepo/firmware/generators/configs/external_nodes/BOSCH_LWS.json
{
    "node_name": "BOSCH_LWS",
    "bus_name": "SCAN",
    "tx": [
        {
            "msg_name": "LWS_Standard",
            "msg_desc": "Standard steering angle and speed",
            "signals": [
                {
                    "sig_name": "LWS_ANGLE",
                    "sig_desc": "Steering Angle",
                    "type": "int16_t",
                    "unit": "deg",
                    "scale": 0.1
                },
                {
                    "sig_name": "LWS_SPEED",
                    "sig_desc": "Angular speed of steering input",
                    "type": "uint8_t",
                    "unit": "deg/s",
                    "scale": 4
                },
                {
                    "sig_name": "OK",
                    "sig_desc": "Sensor failure status, 0 = failure, 1 = OK",
                    "type": "bool"
                },
                {
                    "sig_name": "CAL",
                    "sig_desc": "Sensor calibration status, 0 = uncalibrated, 1 = calibrated",
                    "type": "bool"
                },
                {
                    "sig_name": "TRIM",
                    "sig_desc": "Sensor trim status, 0 = invalid, 1 = valid",
                    "type": "bool"
                },
                {
                    "sig_name": "reserved1",
                    "type": "uint8_t",
                    "length": 5
                },
                {
                    "sig_name": "reserved2",
                    "type": "uint8_t",
                    "length": 8
                }
            ],
            "msg_period": 10,
            "msg_id_override": "0x2B0",
            "msg_priority": 3
        }
    ],
    "rx": []
}

=== PurdueElectricRacing/monorepo/generators/configs/external_nodes/ELCON_CHARGER.json
{
    "node_name": "ELCON_CHARGER",
    "bus_name": "CCAN",
    "tx": [
        {
            "message_name": "elcon_status",
            "description": "Status message from Elcon Charger to A_BOX (Message2)",
            "byte_order": "big_endian",
            "signals": [
                {
                    "signal_name": "charge_voltage",
                    "data_type": "uint16_t",
                    "unit": "V",
                    "scale": 0.1
                },
                {
                    "signal_name": "charge_current",
                    "data_type": "uint16_t",
                    "unit": "A",
                    "scale": 0.1
                },
                {
                    "signal_name": "hw_fail",
                    "description": "Hardware failure",
                    "data_type": "bool"
                },
                {
                    "signal_name": "temp_fail",
                    "description": "Temperature failure",
                    "data_type": "bool"
                },
                {
                    "signal_name": "input_v_fail",
                    "description": "Input voltage failure",
                    "data_type": "bool"
                },
                {
                    "signal_name": "startup_fail",
                    "description": "Startup voltage detection failure",
                    "data_type": "bool"
                },
                {
                    "signal_name": "communication_fail",
                    "description": " 5s timeout from communication failure",
                    "data_type": "bool"
                }
            ],
            "id_override": "0x18FF50E5",
            "period_ms": 1000,
            "priority": 3
        }
    ],
    "rx": [
        {
            "message_name": "elcon_command"
        }
    ]
}

=== PurdueElectricRacing/monorepo/firmware/generators/configs/external_nodes/DAQ_APP.json
{
    "node_name": "DAQ_APP",
    "bus_name": "CCAN",
    "tx": [
        {
            "msg_name": "charge_request",
            "msg_desc": "Message from DAQ App to A_BOX to request charging",
            "signals": [
                {
                    "sig_name": "charge_voltage",
                    "sig_desc": "Requested charge voltage in decivolts",
                    "type": "uint16_t",
                    "unit": "V",
                    "scale": 0.1
                },
                {
                    "sig_name": "charge_current",
                    "sig_desc": "Requested charge current in deciamps",
                    "type": "uint16_t",
                    "unit": "A",
                    "scale": 0.1
                },
                {
                    "sig_name": "charge_enable",
                    "sig_desc": "Request to start charging",
                    "type": "bool"
                },
                {
                    "sig_name": "balance_enable",
                    "sig_desc": "Request to start balancing",
                    "type": "bool"
                }
            ],
            "msg_period": 500,
            "msg_priority": 3
        }
    ],
    "rx": [
        {
            "msg_name": "elcon_status"
        },
        {
            "msg_name": "charging_telemetry"
        }
    ]
}

=== PurdueElectricRacing/monorepo/generators/configs/external_nodes/IZZE_IMU.json
{
    "node_name": "IZZE_IMU",
    "bus_name": "VCAN",
    "tx": [
        {
            "message_name": "IZZE_angular_rate",
            "description": "Angular Rate",
            "byte_order": "big_endian",
            "signals": [
                {
                    "signal_name": "X_axis",
                    "description": "Angular Rate around X-axis",
                    "data_type": "int16_t",
                    "unit": "deg/s",
                    "scale": 0.1
                },
                {
                    "signal_name": "Y_axis",
                    "description": "Angular Rate around Y-axis",
                    "data_type": "int16_t",
                    "unit": "deg/s",
                    "scale": 0.1
                },
                {
                    "signal_name": "Z_axis",
                    "description": "Angular Rate around Z-axis",
                    "data_type": "int16_t",
                    "unit": "deg/s",
                    "scale": 0.1
                },
                {
                    "signal_name": "reserved",
                    "description": "reserved",
                    "data_type": "uint16_t"
                }
            ],
            "period_ms": 50,
            "id_override": "0x4EC",
            "priority": 5
        },
        {
            "message_name": "IZZE_acceleration",
            "description": "Acceleration",
            "byte_order": "big_endian",
            "signals": [
                {
                    "signal_name": "X_axis",
                    "description": "Acceleration along X-axis",
                    "data_type": "int16_t",
                    "unit": "g",
                    "scale": 0.01
                },
                {
                    "signal_name": "Y_axis",
                    "description": "Acceleration along Y-axis",
                    "data_type": "int16_t",
                    "unit": "g",
                    "scale": 0.01
                },
                {
                    "signal_name": "Z_axis",
                    "description": "Acceleration along Z-axis",
                    "data_type": "int16_t",
                    "unit": "g",
                    "scale": 0.01
                },
                {
                    "signal_name": "temperature",
                    "description": "IMU Temperature",
                    "data_type": "int16_t",
                    "unit": "C",
                    "scale": 0.1
                }
            ],
            "period_ms": 50,
            "id_override": "0x4ED",
            "priority": 5
        }
    ],
    "rx": []
}

=== PurdueElectricRacing/monorepo/generators/configs/external_nodes/DAQ_APP.json
{
    "node_name": "DAQ_APP",
    "bus_name": "CCAN",
    "tx": [
        {
            "message_name": "charge_request",
            "description": "Message from DAQ App to A_BOX to request charging",
            "signals": [
                {
                    "signal_name": "charge_voltage",
                    "description": "Requested charge voltage in decivolts",
                    "data_type": "uint16_t",
                    "unit": "V",
                    "scale": 0.1
                },
                {
                    "signal_name": "charge_current",
                    "description": "Requested charge current in deciamps",
                    "data_type": "uint16_t",
                    "unit": "A",
                    "scale": 0.1
                },
                {
                    "signal_name": "charge_enable",
                    "description": "Request to start charging",
                    "data_type": "bool"
                },
                {
                    "signal_name": "balance_enable",
                    "description": "Request to start balancing",
                    "data_type": "bool"
                }
            ],
            "period_ms": 500,
            "priority": 3
        }
    ],
    "rx": [
        {
            "message_name": "elcon_status"
        },
        {
            "message_name": "pack_bms_ccan"
        },
        {
            "message_name": "pack_analog_ccan"
        },
        {
            "message_name": "cell_telemetry_ccan"
        },
        {
            "message_name": "bms_pecs_ccan"
        },
        {
            "message_name": "thermistor_telemetry_ccan"
        }
    ]
}

=== PurdueElectricRacing/monorepo/generators/configs/external_nodes/DAQ_APP_G.json
{
    "node_name": "DAQ_APP_G",
    "bus_name": "GCAN",
    "tx": [
        {
            "message_name": "asdsad",
            "description": "Message from DAQ App to A_BOX to request charging",
            "signals": [
                {
                    "signal_name": "charge_voltage",
                    "description": "Requested charge voltage in decivolts",
                    "data_type": "uint16_t",
                    "unit": "V",
                    "scale": 0.1
                },
                {
                    "signal_name": "charge_current",
                    "description": "Requested charge current in deciamps",
                    "data_type": "uint16_t",
                    "unit": "A",
                    "scale": 0.1
                },
                {
                    "signal_name": "charge_enable",
                    "description": "Request to start charging",
                    "data_type": "bool"
                },
                {
                    "signal_name": "balance_enable",
                    "description": "Request to start balancing",
                    "data_type": "bool"
                }
            ],
            "period_ms": 500,
            "priority": 3
        }
    ],
    "rx": []
}

=== PurdueElectricRacing/monorepo/generators/configs/external_nodes/BOSCH_LWS.json
{
    "node_name": "BOSCH_LWS",
    "bus_name": "VCAN",
    "tx": [
        {
            "message_name": "LWS_Standard",
            "description": "Standard steering angle and speed",
            "signals": [
                {
                    "signal_name": "LWS_ANGLE",
                    "description": "Steering Angle",
                    "data_type": "int16_t",
                    "unit": "deg",
                    "scale": 0.1
                },
                {
                    "signal_name": "LWS_SPEED",
                    "description": "Angular speed of steering input",
                    "data_type": "uint8_t",
                    "unit": "deg/s",
                    "scale": 4
                },
                {
                    "signal_name": "OK",
                    "description": "Sensor failure status, 0 = failure, 1 = OK",
                    "data_type": "bool"
                },
                {
                    "signal_name": "CAL",
                    "description": "Sensor calibration status, 0 = uncalibrated, 1 = calibrated",
                    "data_type": "bool"
                },
                {
                    "signal_name": "TRIM",
                    "description": "Sensor trim status, 0 = invalid, 1 = valid",
                    "data_type": "bool"
                },
                {
                    "signal_name": "reserved1",
                    "data_type": "uint8_t",
                    "length": 5
                },
                {
                    "signal_name": "reserved2",
                    "data_type": "uint8_t",
                    "length": 8
                }
            ],
            "period_ms": 10,
            "id_override": "0x2B0",
            "priority": 5
        }
    ],
    "rx": []
}
